name: f_my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  easy_localization: ^3.0.7
  sqflite: ^2.4.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  lint: ^2.3.0

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  assets:
    - lib/assets/lang/
    - lib/assets/images/azory/
    - lib/assets/images/florencja/
    - lib/assets/images/gibraltar/
    - lib/assets/images/malaga/
    - lib/assets/images/san_marino/
    - lib/assets/images/my/
